BooksAdda/BooksAdda/ViewModels/AssignRoleViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BooksAdda.ViewModels
{
    public class AssignRoleViewModel
    {
        [Required(ErrorMessage = "User is required")]
        public string UserEmail { get; set; }

        public string RoleDescription { get; set; }

        public List<string> Emails { get; set; }

        public List<RoleViewModel> AvailableRoles { get; set; }

        public List<RoleViewModel> SelectedRoles { get; set; }

        [Required(ErrorMessage="Please select atleast one Role")]
        public PostedRoles PostedRoles { get; set; }

        public bool IsAssigned { get; set; }
    }
}

BooksAdda/BooksAdda/Controllers/BookController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BooksAdda.BusinessLayer;
using BooksAdda.CustomAttributes;
using BooksAdda.Pagination;
using BooksAdda.ViewModels;
using System.Collections.Generic;
using BooksAdda.DefinedConstants;


namespace BooksAdda.Controllers
{
    [CustomAuthorizeAttribute(allowedroles = ApplicationConstant.bookControllerAllowedRoles)]
    public class BookController : Controller
    {
        [HttpGet]
        public ViewResult AddBooks()
        {
            BooksRepository repo = new BooksRepository();
            ViewBag.IsAdded = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ViewResult AddBooks(BookViewModel model, HttpPostedFileBase file) // Work while we post page
        {
            BooksRepository repo = new BooksRepository();
            if (ModelState.IsValid)
            {
                //upload book's image
                if (file != null && file.ContentLength > 0)
                {
                    try
                    {
                        string path = Path.Combine(HttpContext.Server.MapPath(ApplicationConstant.imagesFilePath),
                         Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        model.ImageUrl = ApplicationConstant.imagesFilePath + Path.GetFileName(file.FileName);
                        var email = Session["Name"].ToString();
                        ViewBag.IsAdded = repo.AddBook(model, email);
                        ViewBag.FileMessage = "Book was uploaded successfully";
                        ModelState.Clear();
                        model = new BookViewModel();
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("", "Sorry,some error occured while Adding the Book.");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "File invalid");
                    ViewBag.FileMessage = "You have not specified a file.";
                }
            }
            ViewBag.IsAdded = false;
            return View(model);
        }

        public ActionResult UpdateBooks(BookViewModel model)
        {
            BooksRepository repo = new BooksRepository();
            repo.UpdateBook(model);
            if (model.BookId > 0 && model.relatedBookTitle != null)
            {
                repo.AddRelatedBook(model.BookId, model.relatedBookTitle);
            }

            if (model.BookId > 0 && model.tagName != null)
            {
                repo.AddBookTag(model.BookId, model.tagName);
            }
            return RedirectToAction("BookEditById", "Admin", new { bookId = model.BookId });
        }

        public ViewResult BuyBooks(int? page)
        {
            BooksRepository repo = new BooksRepository();
            BuyBooksViewModel model = new BuyBooksViewModel();
            model.Categories = repo.GetBookCategoryList();
            model.RequestedPage = page;
            if (Session["Name"] != null)
            {
                model.Books = repo.GetBookListExceptEmail(Session["Name"].ToString());
                SetPager(model);
            }
            return View(model);
        }

        [HttpPost]
        public ViewResult BuyBooks(BuyBooksViewModel model)
        {
            BooksRepository repo = new BooksRepository();
            model.Categories = repo.GetBookCategoryList();
            if (Session["Name"] != null)
            {
                model.LoggedInUserEmail = Session["Name"].ToString();
                model.Books = repo.GetFilteredBookListExceptEmail(model);
                SetPager(model);
            }
            return View(model);
        }

        // sets the pager values according to model properties
        public BuyBooksViewModel SetPager(BuyBooksViewModel model)
        {
            var pager = new Pager(model.Books.Count(), model.RequestedPage);
            model.Books = model.Books.Skip((pager.CurrentPage - 1) * pager.PageSize).Take(pager.PageSize).ToList();
            model.Pager = pager;
            return model;
        }

        [AllowAnonymous]
        public ViewResult ListBooks(int? page)
        {
            BooksRepository repo = new BooksRepository();
            BuyBooksViewModel model = new BuyBooksViewModel();
            model.Books = repo.GetBookListWithBookCategory();
            model.RequestedPage = page;
            SetPager(model);
            return View(model);
        }

        public ViewResult GetBookById(int bookId)
        {
            BooksRepository repo = new BooksRepository();
            BookViewModel model = repo.GetBookById(bookId);
            model.BuyersEmail = repo.GetBuyerListByBookId(bookId);
            model.RelatedBooks = repo.GetRelatedBooks(bookId);
            model.Tags = repo.GetTagsByBookId(bookId);
            return View(model);
        }

        //get book categories according to paramenter
        public JsonResult GetBookCategoryJson(string term)
        {
            BooksRepository repo = new BooksRepository();
            List<BookCategoryViewModel> categories;
            List<string> list;
            if (String.IsNullOrEmpty(term))
            {
                categories = repo.GetBookCategoryList();
            }
            else
            {
                categories = repo.GetBookCategoryList(term);
            }
            list = categories.Select(y => y.Category).ToList();
            return new JsonResult { Data = list, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetComments(int bookId)
        {
            BooksRepository repo = new BooksRepository();
            List<CommentViewModel> comments = repo.GetComments(bookId);
            comments = comments.Take(8).ToList();
            return new JsonResult { Data = comments, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult ViewNextComments(int bookId, int page)
        {
            BooksRepository repo = new BooksRepository();
            List<CommentViewModel> comments = repo.GetComments(bookId);
            // set pagination for comment
            int totalPages = (int)Math.Ceiling((comments.Count) / (double)ApplicationConstant.commentPerPage);
            if (page < 1 || page > totalPages)
                page = 1;
            comments = comments.Skip(ApplicationConstant.commentPerPage * (page - 1)).
                Take(ApplicationConstant.commentPerPage).ToList();
            return new JsonResult { Data = comments, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult AddComment(string commentDescription, int bookId, string userEmail)
        {
            BooksRepository repo = new BooksRepository();
            repo.AddComment(commentDescription, bookId, userEmail);
            return Json(new { success = true });
        }

        [HttpPost]
        public ViewResult SearchBooks(string searchText)
        {
            BooksRepository repo = new BooksRepository();
            BuyBooksViewModel model = new BuyBooksViewModel();
            model.Categories = repo.GetBookCategoryList();
            model.Books = repo.SearchBooks(searchText);
            SetPager(model);
            return View("BuyBooks", model); // return the same view used for BuyBooks
        }

        public JsonResult GetSortedBooks(string selectedSortProperty)
        {
            BooksRepository repo = new BooksRepository();
            var books = repo.GetSortedBooks(selectedSortProperty);
            return new JsonResult { Data = books, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

BooksAdda/BooksAdda/Controllers/UserController.cs
using BooksAdda.BusinessLayer;
using BooksAdda.CustomAttributes;
using BooksAdda.DefinedConstants;
using BooksAdda.ViewModels;
using System;
using System.Web.Mvc;

namespace BooksAdda.Controllers
{
    [CustomAuthorizeAttribute(allowedroles = ApplicationConstant.userControllerAllowedRoles)]
    public class UserController : Controller
    {
        public ViewResult AddUsers() // Work while we request page  
        {
            return View();
        }

        [HttpPost]
        public ViewResult AddUsers(UserViewModel userViewModel) // Work while we post page  
        {
            UserRepository repo = new UserRepository();
            if (ModelState.IsValid)
            {
                if (repo.AddUser(userViewModel))
                {
                    ViewBag.UserAddedMessage = userViewModel.Name + " " + "was Added Successfully.";
                }
                ModelState.Clear();
            }
            return View(userViewModel);
        }

        public ViewResult GetUserByEmail(string email) // Work while we request page  
        {
            UserRepository repo = new UserRepository();
            UserEditViewModel user = repo.GetUserDetailsByEmail(email);
            ViewBag.EditMessage = TempData["EditMessage"];
            return View(user);
        }

        [HttpPost]
        public ActionResult EditUsers(UserEditViewModel userViewModel) // Work while we request page  
        {
            UserRepository repo = new UserRepository();
            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateUser(userViewModel);
                    ViewBag.EditMessage = "Hi" + " " + userViewModel.Name + ". " + "Your Account has been Updated";
                    ModelState.Clear();
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Invalid Update");
                }
            }
            return View("GetUserByEmail", userViewModel);
        }
    }
}

BooksAdda/BooksAdda/Views/Admin/AddRole.cshtml
@section Head
    {
    @Styles.Render("~/Content/AddRole")
}
@{
    ViewBag.Title = "AddRole";
}
@model BooksAdda.ViewModels.RoleViewModel
<h3 class="top-label">Add Role</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoleDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2  col-md-10">
                <input type="submit" value="Create" class="Action_btn" />
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jquery")

@if (Model.IsAdded)
{
    <script src="~/Scripts/success-notify.js"></script>
}

BooksAdda/BooksAdda/Views/Admin/AdminHomepage.cshtml
@section Head
    {
    @Styles.Render("~/Content/AdminHomepage")
}
@{
    ViewBag.Title = "Adminpage";
}
<body>
    <a href="/User/AddUsers"><div class="Thumbnail_Btn">Add User</div></a>
    <a href="/Admin/EditDeleteUser"><div class="Thumbnail_Btn">Edit/Delete User</div></a>
    <a href="/Admin/AddRole"><div class="Thumbnail_Btn">Add Role</div></a>
    <a href="/Admin/AssignRole"><div class="Thumbnail_Btn">Assign Role</div></a>
    <a href="/Admin/DeleteRole"><div class="Thumbnail_Btn">Delete Role</div></a>
    <a href="/Admin/EditDeleteBook"><div class="Thumbnail_Btn">Edit/Delete Book</div></a>
</body>

BooksAdda/BooksAdda/Views/Admin/AssignRole.cshtml
@section Head{
@Styles.Render("~/Content/AssignRole")
}
@{
    ViewBag.Title = "AssignRole";
}
@model BooksAdda.ViewModels.AssignRoleViewModel
<h3 class="top-label">Assign Role</h3>
<div class="assign_role_form">
    @using (Html.BeginForm())
    {
        <p>
            @Html.DropDownListFor(model => model.UserEmail,
                new SelectList(Model.Emails),
                "Select User",
                new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
        </p>
        <p>
            @Html.CheckBoxListFor(model => model.PostedRoles.RoleIds,
                                  model => model.AvailableRoles,
                                  role => role.RoleId,
                                  role => role.RoleDescription,
                                  model => model.SelectedRoles
                                  )
        </p>
        <p>@Html.ValidationMessageFor(model => model.PostedRoles, "", new { @class = "text-danger" })</p>
        <p>
            <input id="assignbtn" class="Action_btn" type="submit" value="Assign Role" />
        </p>
    }
</div>
@if (Model.IsAssigned)
{
    <script src="~/Scripts/success-notify.js"></script>
}

BooksAdda/BooksAdda/Views/Admin/BookEditById.cshtml
@model BooksAdda.ViewModels.BookViewModel
@section Head{
@Styles.Render("~/Content/EditBookById")
}

<h3 class="top-label">    
    Edit Book
</h3>
<img src="@Url.Content(@Model.ImageUrl)" class="book_img" alt="image" />
<div id="divBook"></div>
@using (Ajax.BeginForm("UpdateBooks", "Book", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.HiddenFor(model => model.BookId)
        <input type="hidden" id="BookId" value=@Model.BookId />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PrintedPrice, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PrintedPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrintedPrice, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DiscountedPrice, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.DiscountedPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiscountedPrice, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <p class="col-md-4"></p>
            <div class="col-md-8">
                @foreach (var book in Model.RelatedBooks)
                {
                    <span class="title-item-removable">
                        <span class="title-label" id=@book.BookId>@book.Title</span>
                        <span class="book-remove-btn">X</span>
                    </span>
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.relatedBookTitle, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.relatedBookTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.relatedBookTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <p class="col-md-4"></p>
            <div class="col-md-8">
                @foreach (var tag in Model.Tags)
                {
                    <span class="title-item-removable"><span class="title-label" id=@tag>@tag</span><span class="tag-remove-btn">X</span></span>
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.tagName, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.tagName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tagName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" value="Update" class="Action_btn" id="editbook-update-btn" />
            </div>
        </div>
    </div>
}
<p class="clear"></p>



@if (Model.RelatedBooks.Any())
{
    <h3 class="top-label">Related Books</h3>
    foreach (var book in Model.RelatedBooks)
    {
        <div class="box">
            <p>
                <a href="@Url.Action("GetBookById", "Book", new { BookId = @book.BookId })">
                    <img class="related_book_img" src="@book.ImageUrl" />
                </a>
            </p>
            <p class="book_info">
                <label>DiscountedPrice:</label>
                @book.DiscountedPrice
            </p>
        </div>
    }
}
@Scripts.Render("~/bundles/editbookbyid")

BooksAdda/BooksAdda/Views/Admin/DeleteRole.cshtml
@section Head{
@Styles.Render("~/Content/DeleteRole")
}

@model BooksAdda.ViewModels.RoleViewModel
<h3 class="top-label">Delete Role</h3>
<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoleDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoleDescription,
                    new SelectList(Model.Roles, "RoleDescription"),
                    "Select Role",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2  col-md-10">
                <input id="submit_btn" type="submit" value="Delete" class="Action_btn confirm_button" />
            </div>
        </div>
    </div>
    }
</div>
@Scripts.Render("~/bundles/jquery")

@if (Model.IsDeleted)
{
    <script src="~/Scripts/success-notify.js"></script>
}

<script type="text/javascript">
    $(".confirm_button").click(function (e) {
        if (!confirm("Confirm delete?")) {
            //if user clicks cancel,avoid submitting data
            $("#submit_btn").attr("type", "button");
        }
        else {
            //if user clicks ok, submit data
            $("#submit_btn").attr("type", "submit");
        }
    });
</script>

BooksAdda/BooksAdda/Views/Admin/EditDeleteBook.cshtml
@model BooksAdda.ViewModels.BuyBooksViewModel
@section Head{
@Styles.Render("~/Content/EditBooks")
}
<h3 class="top-label">Edit or Delete Books</h3>
<br />
@if (Model.Books.Any())
{
    foreach (var book in Model.Books)
    {
        <div>
            <p class="col-md-8">
                <a href="@Url.Action("GetBookById", "Book", new { BookId = @book.BookId })">
                    <img class="book_img " src="@book.ImageUrl" />
                </a>
                @book.Title
            </p>
            <p class="col-md-4">
                <a href="/Admin/BookEditById?bookId=@book.BookId">
                    <button class="Action_btn_modified">
                        <span class="glyphicon glyphicon-pencil"></span>
                        Edit
                    </button>
                </a>

                <a href="/Admin/DeleteBookById?id=@book.BookId">
                    <input type="hidden" class="book_id" value=@book.BookId>
                    <button class="Action_btn_modified confirm_button">
                        <span class="glyphicon glyphicon-trash"></span>
                        Delete
                    </button>
                </a>
            </p>

        </div>
    }
}
<input type="hidden" value=@Model.Pager.CurrentPage id="CurrentPage">

<div class="container">
    <div class="col-md-6 col-md-offset-3">

        <!-- pager -->
        @if (Model.Pager.EndPage > 1)
        {
            <ul class="pagination">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li>
                        <a href="~/Admin/EditDeleteBook">First</a>
                    </li>
                    <li>
                        <a href="~/Admin/EditDeleteBook?page=@(Model.Pager.CurrentPage - 1)">Previous</a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
                        <a href="~/Admin/EditDeleteBook?page=@page">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li>
                        <a href="~/Admin/EditDeleteBook?page=@(Model.Pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li>
                        <a href="~/Admin/EditDeleteBook?page=@(Model.Pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </div>
</div>
<script type="text/javascript">
    $(".confirm_button").click(function (e) {
        var book_id = $(this).prev().val();
        var currPage = $("#CurrentPage").val();
        if (!confirm("Confirm delete?")) {
            //if user clicks cancel,avoid submitting data
            $(this).parent().attr("href", "#");
        }
        else {
            //if user clicks ok, submit data
            $(this).parent().attr("href", "/Admin/DeleteBookById?id=" + book_id + "&&page=" + currPage);
        }
    });
</script>

BooksAdda/BooksAdda/Views/Admin/EditDeleteUser.cshtml
@model BooksAdda.ViewModels.UserListViewModel
@section Head{
@Styles.Render("~/Content/DeleteUser")
}
<h3 class="top-label">Edit or Delete Users</h3>
<br />
@foreach (var user in Model.Users)
{
    <div>
        <p class="col-md-8 user-container">
            @Html.ActionLink(@user.Email, "GetUserByEmail", "User", new { Email = @user.Email }, null)
        </p>
        <p class="col-md-4 button-container">
            <a href="/User/GetUserByEmail?email=@user.Email">
                <button class="Action_btn_modified">
                    <span class="glyphicon glyphicon-pencil"></span>
                    Edit
                </button>
            </a>
            <input type="hidden" class="email" value=@user.Email />
            <button class="Action_btn_modified confirm_button">
                <span class="glyphicon glyphicon-trash"></span>
                @Html.ActionLink("Delete", "Delete", "Admin")
            </button>
        </p>
    </div>
}

<input type="hidden" value=@Model.Pager.CurrentPage id="CurrentPage">
<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <!-- pager -->
        @if (Model.Pager.EndPage > 1)
        {
            <ul class="pagination">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li>
                        <a href="~/Admin/EditDeleteUser">First</a>
                    </li>
                    <li>
                        <a href="~/Admin/EditDeleteUser?page=@(Model.Pager.CurrentPage - 1)">Previous</a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
                        <a href="~/Admin/EditDeleteUser?page=@page">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li>
                        <a href="~/Admin/EditDeleteUser?page=@(Model.Pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li>
                        <a href="~/Admin/EditDeleteUser?page=@(Model.Pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </div>
</div>

<script type="text/javascript">
    $(".confirm_button").click(function (e) {
        var email = $(this).prev().val();
        var currPage = $("#CurrentPage").val();
        if (!confirm("Confirm delete?")) {
            //if user clicks cancel,avoid submitting data
            $(this).children().attr("href", "#");
        }
        else {
            //if user clicks ok, submit data
            $(this).children().attr("href", "/Admin/Delete?email=" + email + "&&page=" + currPage);
        }
    });
</script>