BooksAdda/BooksAdda/ViewModels/BookViewModel.cs
using BooksAdda.CustomAttributes;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BooksAdda.ViewModels
{
    public class BookViewModel
    {
        [Required]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "Title must be between 4 and 50 characters")]
        public string Title { get; set; }

        [Required]
        public string Category { get; set; }

        [StringLength(100, MinimumLength=4, ErrorMessage = "Details must be between 4 and 100 characters")]
        [Required]
        public string Details { get; set; }

        [Display(Name="Printed Price")]
        [Required]
        [RegularExpression(@"^[0-9]+$",ErrorMessage = "Invalid Printed Price")]
        public short PrintedPrice { get; set; }

        [Display(Name = "Discounted Price")]
        [Required]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Invalid Printed Price")]
        [LesserThanAttribute("PrintedPrice")]
        public short DiscountedPrice { get; set; }

        public string ImageUrl { get; set; }

        public string SellerEmail { get; set; }

        public string BuyerEmail { get; set; }

        public List<string> BuyersEmail { get; set; }

        public List<BookViewModel> RelatedBooks { get; set; }

        public List<string> Tags { get; set; }

        [Display(Name = "Related Books")]
        public string relatedBookTitle { get; set; }

        [Display(Name = "Tags")]
        public string tagName { get; set; }

        public int BookId { get; set; }

        public bool IsAdded { get; set; }

        public bool IsDeleted { get; set; }
    }
}

BooksAdda/BooksAdda/ViewModels/BuyBooksViewModel.cs
using BooksAdda.Pagination;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BooksAdda.ViewModels
{
    public class BuyBooksViewModel
    {
        public List<BookViewModel> Books { get; set; }

        public Pager Pager { get; set; }

        public int? RequestedPage { get; set; }

        public List<BookCategoryViewModel> Categories { get; set; }

        public string LoggedInUserEmail { get; set; }

        // filtering data

        [Required(ErrorMessage="Please select a Category")]
        public int SelectedCategoryId { get; set; }

        [Required(ErrorMessage="Please select minimum price")]
        public int PriceMin { get; set; }

        [Required(ErrorMessage="Please select maximum price")]
        public int PriceMax { get; set; }

        [Display(Name = "Sort Books By")]
        public string SortBy { get; set; }

        public bool IsDeleted { get; set; }
    }
}

BooksAdda/BooksAdda/Controllers/BookController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BooksAdda.BusinessLayer;
using BooksAdda.CustomAttributes;
using BooksAdda.Pagination;
using BooksAdda.ViewModels;
using System.Collections.Generic;
using BooksAdda.DefinedConstants;


namespace BooksAdda.Controllers
{
    [CustomAuthorizeAttribute(allowedroles = ApplicationConstant.bookControllerAllowedRoles)]
    public class BookController : Controller
    {
        [HttpGet]
        public ViewResult AddBooks()
        {
            BooksRepository repo = new BooksRepository();
            ViewBag.IsAdded = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ViewResult AddBooks(BookViewModel model, HttpPostedFileBase file) // Work while we post page
        {
            BooksRepository repo = new BooksRepository();
            if (ModelState.IsValid)
            {
                //upload book's image
                if (file != null && file.ContentLength > 0)
                {
                    try
                    {
                        string path = Path.Combine(HttpContext.Server.MapPath(ApplicationConstant.imagesFilePath),
                         Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        model.ImageUrl = ApplicationConstant.imagesFilePath + Path.GetFileName(file.FileName);
                        var email = Session["Name"].ToString();
                        ViewBag.IsAdded = repo.AddBook(model, email);
                        ViewBag.FileMessage = "Book was uploaded successfully";
                        ModelState.Clear();
                        model = new BookViewModel();
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("", "Sorry,some error occured while Adding the Book.");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "File invalid");
                    ViewBag.FileMessage = "You have not specified a file.";
                }
            }
            ViewBag.IsAdded = false;
            return View(model);
        }

        public ActionResult UpdateBooks(BookViewModel model)
        {
            BooksRepository repo = new BooksRepository();
            repo.UpdateBook(model);
            if (model.BookId > 0 && model.relatedBookTitle != null)
            {
                repo.AddRelatedBook(model.BookId, model.relatedBookTitle);
            }

            if (model.BookId > 0 && model.tagName != null)
            {
                repo.AddBookTag(model.BookId, model.tagName);
            }
            return RedirectToAction("BookEditById", "Admin", new { bookId = model.BookId });
        }

        public ViewResult BuyBooks(int? page)
        {
            BooksRepository repo = new BooksRepository();
            BuyBooksViewModel model = new BuyBooksViewModel();
            model.Categories = repo.GetBookCategoryList();
            model.RequestedPage = page;
            if (Session["Name"] != null)
            {
                model.Books = repo.GetBookListExceptEmail(Session["Name"].ToString());
                SetPager(model);
            }
            return View(model);
        }

        [HttpPost]
        public ViewResult BuyBooks(BuyBooksViewModel model)
        {
            BooksRepository repo = new BooksRepository();
            model.Categories = repo.GetBookCategoryList();
            if (Session["Name"] != null)
            {
                model.LoggedInUserEmail = Session["Name"].ToString();
                model.Books = repo.GetFilteredBookListExceptEmail(model);
                SetPager(model);
            }
            return View(model);
        }

        // sets the pager values according to model properties
        public BuyBooksViewModel SetPager(BuyBooksViewModel model)
        {
            var pager = new Pager(model.Books.Count(), model.RequestedPage);
            model.Books = model.Books.Skip((pager.CurrentPage - 1) * pager.PageSize).Take(pager.PageSize).ToList();
            model.Pager = pager;
            return model;
        }

        [AllowAnonymous]
        public ViewResult ListBooks(int? page)
        {
            BooksRepository repo = new BooksRepository();
            BuyBooksViewModel model = new BuyBooksViewModel();
            model.Books = repo.GetBookListWithBookCategory();
            model.RequestedPage = page;
            SetPager(model);
            return View(model);
        }

        public ViewResult GetBookById(int bookId)
        {
            BooksRepository repo = new BooksRepository();
            BookViewModel model = repo.GetBookById(bookId);
            model.BuyersEmail = repo.GetBuyerListByBookId(bookId);
            model.RelatedBooks = repo.GetRelatedBooks(bookId);
            model.Tags = repo.GetTagsByBookId(bookId);
            return View(model);
        }

        //get book categories according to paramenter
        public JsonResult GetBookCategoryJson(string term)
        {
            BooksRepository repo = new BooksRepository();
            List<BookCategoryViewModel> categories;
            List<string> list;
            if (String.IsNullOrEmpty(term))
            {
                categories = repo.GetBookCategoryList();
            }
            else
            {
                categories = repo.GetBookCategoryList(term);
            }
            list = categories.Select(y => y.Category).ToList();
            return new JsonResult { Data = list, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetComments(int bookId)
        {
            BooksRepository repo = new BooksRepository();
            List<CommentViewModel> comments = repo.GetComments(bookId);
            comments = comments.Take(8).ToList();
            return new JsonResult { Data = comments, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult ViewNextComments(int bookId, int page)
        {
            BooksRepository repo = new BooksRepository();
            List<CommentViewModel> comments = repo.GetComments(bookId);
            // set pagination for comment
            int totalPages = (int)Math.Ceiling((comments.Count) / (double)ApplicationConstant.commentPerPage);
            if (page < 1 || page > totalPages)
                page = 1;
            comments = comments.Skip(ApplicationConstant.commentPerPage * (page - 1)).
                Take(ApplicationConstant.commentPerPage).ToList();
            return new JsonResult { Data = comments, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult AddComment(string commentDescription, int bookId, string userEmail)
        {
            BooksRepository repo = new BooksRepository();
            repo.AddComment(commentDescription, bookId, userEmail);
            return Json(new { success = true });
        }

        [HttpPost]
        public ViewResult SearchBooks(string searchText)
        {
            BooksRepository repo = new BooksRepository();
            BuyBooksViewModel model = new BuyBooksViewModel();
            model.Categories = repo.GetBookCategoryList();
            model.Books = repo.SearchBooks(searchText);
            SetPager(model);
            return View("BuyBooks", model); // return the same view used for BuyBooks
        }

        public JsonResult GetSortedBooks(string selectedSortProperty)
        {
            BooksRepository repo = new BooksRepository();
            var books = repo.GetSortedBooks(selectedSortProperty);
            return new JsonResult { Data = books, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

BooksAdda/BooksAdda/Controllers/NotifyController.cs
using BooksAdda.BusinessLayer;
using BooksAdda.CustomAttributes;
using BooksAdda.DefinedConstants;
using BooksAdda.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BooksAdda.Controllers
{
    [CustomAuthorizeAttribute(allowedroles = ApplicationConstant.notifyControllerAllowedRoles)]
    public class NotifyController : Controller
    {
        public ActionResult CreateNotification(int bookId, string buyerEmail, string sellerEmail)
        {
            NotificationRepository repo = new NotificationRepository();
            repo.CreateNotification(bookId, buyerEmail, sellerEmail);
            return RedirectToAction("GetBookById", "Book", new { BookId = bookId });
        }

        public ActionResult DeleteNotification(int bookId, string buyerEmail)
        {
            NotificationRepository repo = new NotificationRepository();
            repo.DeleteNotification(bookId, buyerEmail);
            return RedirectToAction("GetBookById", "Book", new { bookId = bookId });

        }
        public ViewResult ShowNotificationByEmail(string email)
        {
            NotificationRepository repo = new NotificationRepository();
            List<NotificationViewModel> notificationList = repo.ListNotificationByEmail(email);
            return View(notificationList);
        }
    }
}

BooksAdda/BooksAdda/Controllers/UserController.cs
using BooksAdda.BusinessLayer;
using BooksAdda.CustomAttributes;
using BooksAdda.DefinedConstants;
using BooksAdda.ViewModels;
using System;
using System.Web.Mvc;

namespace BooksAdda.Controllers
{
    [CustomAuthorizeAttribute(allowedroles = ApplicationConstant.userControllerAllowedRoles)]
    public class UserController : Controller
    {
        public ViewResult AddUsers() // Work while we request page  
        {
            return View();
        }

        [HttpPost]
        public ViewResult AddUsers(UserViewModel userViewModel) // Work while we post page  
        {
            UserRepository repo = new UserRepository();
            if (ModelState.IsValid)
            {
                if (repo.AddUser(userViewModel))
                {
                    ViewBag.UserAddedMessage = userViewModel.Name + " " + "was Added Successfully.";
                }
                ModelState.Clear();
            }
            return View(userViewModel);
        }

        public ViewResult GetUserByEmail(string email) // Work while we request page  
        {
            UserRepository repo = new UserRepository();
            UserEditViewModel user = repo.GetUserDetailsByEmail(email);
            ViewBag.EditMessage = TempData["EditMessage"];
            return View(user);
        }

        [HttpPost]
        public ActionResult EditUsers(UserEditViewModel userViewModel) // Work while we request page  
        {
            UserRepository repo = new UserRepository();
            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateUser(userViewModel);
                    ViewBag.EditMessage = "Hi" + " " + userViewModel.Name + ". " + "Your Account has been Updated";
                    ModelState.Clear();
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Invalid Update");
                }
            }
            return View("GetUserByEmail", userViewModel);
        }
    }
}

BooksAdda/BooksAdda/Views/Book/AddBooks.cshtml
@model BooksAdda.ViewModels.BookViewModel
@section Head{
    @Styles.Render("~/Content/AddBooks")    
}
@{
    ViewBag.Title = "Add Books";
}
<h2 class="top-label">Add your Book</h2>
@if (ViewBag.FileMessage != null)
{
    <div class="update_message">
        @ViewBag.FileMessage
    </div>
}
<br />
<body>
    <div class="form-horizontal">
        @using (Html.BeginForm("AddBooks",
                                    "Book",
                                    FormMethod.Post,
                                    new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrintedPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PrintedPrice, new { htmlAttributes = new { @class = "form-control", maxlength = "5" } })
                    @Html.ValidationMessageFor(model => model.PrintedPrice, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiscountedPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiscountedPrice, new { htmlAttributes = new { @class = "form-control", maxlength = "5"} })
                    @Html.ValidationMessageFor(model => model.DiscountedPrice, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="file" class="control-label col-md-2">Upload Image:</label>
                <div class="col-md-10">
                    <input type="file" name="file" id="file" class="form-control" data-val="true" data-val-required="File is required" />
                    <span class="text-danger field-validation-error" data-valmsg-for="file" data-valmsg-replace="true"></span>

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add" class="Action_btn" />
                </div>
            </div>
        }
    </div>     
</body>
@Scripts.Render("~/bundles/jquery")
@if (ViewBag.IsAdded)
{
    <script src="~/Scripts/successMessage.js"></script>
}

BooksAdda/BooksAdda/Views/Book/BuyBooks.cshtml
@model BooksAdda.ViewModels.BuyBooksViewModel
@section Head{
    @Styles.Render("~/Content/BuyBooks")
}
@{
    ViewBag.Title = "Buy Books";
}
<h2 class="top-label">Buy Books</h2>
@using (Html.BeginForm())
{
    <div class="filter_top row">
        <div class="col-md-6">
            @Html.DropDownListFor(model => model.SelectedCategoryId,
    new SelectList(Model.Categories, "Id", "Category"),
    "Select Category",
    new { @class = "form-control" })
            <strong> Price :</strong>
            @Html.DropDownListFor(model => model.PriceMin,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "0" , Text = "0" },
                       new SelectListItem { Value = "100" , Text = "100" },
                       new SelectListItem { Value = "500" , Text = "500" },
                       new SelectListItem { Value = "1000" , Text = "1000" }
                    },
                  new { @class = "myselect" })
            <strong>&nbsp; - &nbsp;</strong>

            @Html.DropDownListFor(model => model.PriceMax,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "100" , Text = "100" },
                       new SelectListItem { Value = "500" , Text = "500" },
                       new SelectListItem { Value = "1000" , Text = "1000" }
                    },
                  new { @class = "myselect" })
            <br />
            <input type="submit" value="Filter Books" class="Action_btn" />
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.SortBy)
            @Html.DropDownListFor(model => model.SortBy,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "Title" , Text = "Title" },
                       new SelectListItem { Value = "Details" , Text = "Details" },
                       new SelectListItem { Value = "DiscountedPrice" , Text = "DiscountedPrice" }
                    },
      new { @class = "form-control", @onchange = "getSortedBooks()" })
        </div>
    </div>
}
<div id="bookcontainer">
    @if (Model.Books.Any())
    {
        foreach (var book in Model.Books)
        {
            <div class="box">
                <p>
                    <a href="@Url.Action("GetBookById", "Book", new { BookId = @book.BookId })">
                        <img class="book_img" src="@book.ImageUrl" />
                    </a>
                </p>
                <p class="book_info">
                    <label>DiscountedPrice:</label>
                    @book.DiscountedPrice
                </p>
            </div>
        }
    }
    else
    {
        <h3 class="centre-text">No Books</h3>
    }
</div>
<div class="clear"></div>

<div class="container">
    <div class="col-md-6 col-md-offset-3">

        <!-- pager -->
        @if (Model.Pager.EndPage > 1)
        {
            <ul class="pagination">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li>
                        <a href="~/Book/BuyBooks">First</a>
                    </li>
                    <li>
                        <a href="~/Book/BuyBooks?page=@(Model.Pager.CurrentPage - 1)">Previous</a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
                        <a href="~/Book/BuyBooks?page=@page">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li>
                        <a href="~/Book/BuyBooks?page=@(Model.Pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li>
                        <a href="~/Book/BuyBooks?page=@(Model.Pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </div>
</div>
<script src="~/Scripts/book-sort.js"></script>

BooksAdda/BooksAdda/Views/Book/GetBookById.cshtml
@model BooksAdda.ViewModels.BookViewModel
@section Head{
@Styles.Render("~/Content/GetBookById")   
}
@if (Model.Tags.Any())
{
    <div class="tag-container">
        <h3><span class="glyphicon glyphicon-tags"></span><label>Tagged In</label></h3>
        @foreach (var tag in Model.Tags)
        {
            <span class="tag">@tag</span>
        }
    </div>
}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="@Url.Content(@Model.ImageUrl)" class="book_img" alt="image" />
        </div>
        <div class="col-md-8">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Details)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Details)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PrintedPrice)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PrintedPrice)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DiscountedPrice)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DiscountedPrice)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BookId)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BookId)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Category)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Category)
                </dd>
                <dd>
                    <p class="link_blue">
                        @Html.ActionLink("Seller", "GetUserByEmail", "User", new { email = @Model.SellerEmail }, null)
                    </p>
                </dd>
            </dl>
        </div>
    </div>
    <div class="clear"></div>
    @if (Session["Name"] != null)
    {
        var interested = false;
        if (Model.BuyersEmail != null)
        {
            foreach (var item in @Model.BuyersEmail)
            {
                if (item == Session["Name"].ToString())
                {
                    interested = true;
                }
            }
        }

        if (interested == false)
        {
            <button class="Action_btn">
                @Html.ActionLink("Show Interest", "CreateNotification", "Notify", new
                      {
                          SellerEmail = @Model.SellerEmail,
                          BookId = @Model.BookId,
                          BuyerEmail = @Session["Name"]
                      }, null)
            </button>

        }

        else
        {
            <button class="Action_btn">
                @Html.ActionLink("Cancel Interest", "DeleteNotification", "Notify", new
                           {
                               BookId = @Model.BookId,
                               BuyerEmail = @Session["Name"]
                           }, null)
            </button>
        }
    }
    <br />
    <input type="hidden" id="session_name" value=@Session["Name"]>
    <input type="hidden" id="bookid" value=@Model.BookId />
    <textarea rows="2" cols="30" class="typedcomment"></textarea>
    <button id="commentpost" value="Comment" class="Action_btn">Comment</button>
    <div id="viewpreviouscomments">
        View previous Comments
    </div>
    <div class="displaycomment">
    </div>
    <div id="viewnextcomments">
        View next Comments
    </div>

</div>

@if (Model.RelatedBooks.Any())
{
    <hr />
    <h3 class="top-label"><label>Similar Books</label></h3>
    foreach (var book in Model.RelatedBooks)
    {
        <div class="box">
            <p>
                <a href="@Url.Action("GetBookById", "Book", new { BookId = @book.BookId })">
                    <img class="related_book_img" src="@book.ImageUrl" />
                </a>
            </p>
            <p class="book_info">
                <label>DiscountedPrice:</label>
                @book.DiscountedPrice
            </p>
        </div>
    }
}
@Scripts.Render("~/bundles/getbookbyid")

BooksAdda/BooksAdda/Views/Book/GetComments.cshtml
@model IEnumerable<BooksAdda.ViewModels.CommentViewModel>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CommentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CommentDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserEmail)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CommentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CommentDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserEmail)
            </td>

        </tr>
    }

</table>

BooksAdda/BooksAdda/Views/Book/ListBooks.cshtml
@section Head{
    @Styles.Render("~/Content/ListBooks.css")
}
@model BooksAdda.ViewModels.BuyBooksViewModel
<h2 class="top-label">Available Books</h2>

<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Details
        </th>
        <th>
            PrintedPrice
        </th>
        <th>
            DiscountedPrice
        </th>
        <th>
            Category
        </th>
        <th>
            Seller Email
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Books)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrintedPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscountedPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SellerEmail)
            </td>

        </tr>
    }

</table>
<div class="container">
    <div class="col-md-6 col-md-offset-3">

        <!-- pager -->
        @if (Model.Pager.EndPage > 1)
        {
            <ul class="pagination">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li>
                        <a href="~/Book/ListBooks">First</a>
                    </li>
                    <li>
                        <a href="~/Book/ListBooks?page=@(Model.Pager.CurrentPage - 1)">Previous</a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
                        <a href="~/Book/ListBooks?page=@page">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li>
                        <a href="~/Book/ListBooks?page=@(Model.Pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li>
                        <a href="~/Book/ListBooks?page=@(Model.Pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </div>
</div>

BooksAdda/BooksAdda/Views/Book/SearchBooks.cshtml
@section Head{
    @Styles.Render("~/Content/BuyBooks.css")
}
@model BooksAdda.ViewModels.BuyBooksViewModel
@foreach (var book in Model.Books)
{
    <div class="box">
        <p>
            <a href="@Url.Action("GetBookById", "Book", new { BookId = @book.BookId })"><img class="book_img" src="@Url.Content(@book.ImageUrl)" /></a>
        </p>
        <p class="book_info">
            <label>DiscountedPrice:</label>
            @book.DiscountedPrice
        </p>
    </div>
}
<div class="clear"></div>